### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by frangarcia** [gpc/export#13]
I was thinking that it would be great to improve the documentation of this plugin. The info at https://grails.org/plugin/export is very outdated and it needs to be updated. 

I was thinking taking advantage of github pages (as some other grails plugins e.g. at https://github.com/grails-plugins/grails-spring-security-core/tree/gh-pages).

We could even have different documentation for different versions when needed. What do you think about it?

**Comment by puneetbehl** [comment]
@frangarcia, though I have sent pull request for updated documentation but you could also refer http://puneetbehl.github.io/grails-export/

**Comment by frangarcia** [comment]
Woow, you have done a very good job. Congrats!
